# Config file for https://travis-ci.org/
# Validate this file here - http://lint.travis-ci.org/

language: php

php:
    - 7.1
    - 7.2

install:
  - travis_retry composer install --no-interaction --no-suggest
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

before_script:
    - mkdir -p build/logs
    - ls -al

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_success:
 - travis_retry php coveralls.phar -v
 - bash <(curl -s https://codecov.io/bash)

branches:
  only: master

cache:
  directories:
  - vendor
  - $HOME/.cache/composer
